x-airflow-common: &airflow-common
  build: ./docker/airflow
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "32769:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 10
      timeout: 5s

  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - "32767:8080"
    depends_on:
      - postgres

  namenode:
    image: apache/hadoop:3
    container_name: namenode
    hostname: namenode
    restart: always
    command: ["hdfs", "namenode"]
    ports:
      - "32763:9870"
    environment:
      - ENSURE_NAMENODE_DIR=/hadoop/dfs/name
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - hadoop-namenode:/hadoop/dfs/name
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      retries: 10
      timeout: 5s

  datanode:
    image: apache/hadoop:3
    container_name: datanode
    hostname: datanode
    restart: always
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - hadoop-datanode:/hadoop/dfs/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 10s
      retries: 10
      timeout: 5s

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    hostname: hive-metastore
    restart: always
    depends_on:
      - namenode
      - datanode
      - postgres
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - IS_RESUME=true
    volumes:
      - ./config/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
    ports:
      - "32761:9083"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 10s
      retries: 10
      timeout: 5s

  hive-server:
    image: apache/hive:4.0.0
    container_name: hive-server
    hostname: hive-server
    restart: always
    depends_on:
      - hive-metastore
    environment:
      - SERVICE_NAME=hiveserver2
      - IS_RESUME=true
    volumes:
      - ./config/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
    ports:
      - "32760:10000"
      - "32759:10002"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 10s
      retries: 10
      timeout: 5s


  spark-master:
    image: bitnamilegacy/spark:3.5
    container_name: spark-master
    hostname: spark-master
    restart: always
    environment:
      - SPARK_MODE=master
    ports:
      - "32766:8080"
      - "32765:7077"
    volumes:
      - ./mnt/spark/apps:/opt/spark-apps
      - ./mnt/spark/data:/opt/spark-data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      retries: 10
      timeout: 5s

  spark-worker:
    image: bitnamilegacy/spark:3.5
    container_name: spark-worker
    hostname: spark-worker
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "32764:8081"
    volumes:
      - ./mnt/spark/apps:/opt/spark-apps
      - ./mnt/spark/data:/opt/spark-data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      retries: 10
      timeout: 5s


  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: "true"

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5

######################################################
# VOLUMES
######################################################
volumes:
  postgres-db-volume:
  hadoop-namenode:
  hadoop-datanode:

######################################################
# NETWORK
######################################################
networks:
  default:
    name: my-structure-network
